"""Method 7 — does Atlas's anomaly SELECTION (joint anomalies) produce
better hypotheses than aigraph's native anomalies, regardless of prompting?

Reuses two existing hypothesis populations under the SAME workflow (forward-
frame + reflect, "C"):

  Population J (joint anomalies, Atlas-selected):
    hP entries in artifacts/atlas_test/m2_out.jsonl
    (n=11; from method2 Arm P — joint anomalies but with Atlas context
    stripped, so the source is the only Atlas-touched dimension).

  Population N (non-joint anomalies, aigraph-native):
    hC entries in artifacts/atlas_test/genexp16_out.jsonl
    (n=16; from the genexp16 anomalies sampled from val1-primary).

Both populations were generated by Workflow C (forward-frame + reflect),
which controls the workflow variable. The only difference is anomaly source.

For each hyp: find top-5 Atlas bottleneck quotes (same TF-IDF as Method 3)
then a single Kimi Likert call with the Method 3 axes.

Emits a single judge-input JSONL that the existing run_method3_judge.py
can score. No new server-side code.
"""
from __future__ import annotations

import json
import math
import re
import sys
from collections import Counter
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
JOINT_ANOMALIES = _REPO / "artifacts/atlas_test/joint_anomalies.jsonl"
M2_OUT = _REPO / "artifacts/atlas_test/m2_out.jsonl"
GENEXP_OUT = _REPO / "artifacts/atlas_test/genexp16_out.jsonl"
QUOTES_OUT = _REPO / "artifacts/atlas_test/method3_atlas_quotes.jsonl"

_TOKEN = re.compile(r"[A-Za-z][A-Za-z0-9_-]{2,}")
_STOP = set("""
the a an and or of to in for on at by with from is are was were be been being
this that these those it its as which whether also we us our paper papers
method methods using uses used result results approach approaches model
models task tasks based introduce introduces introduced propose proposes
proposed work works show shows demonstrated demonstrate evaluate evaluation
training train inference learning learned learn data dataset datasets large
new novel can will may could would should they them their not but if then
than so such all any more most some many one two three four five however
moreover thus therefore while when where what who why because between
""".split())


def tokenize(t: str) -> list[str]:
    return [s.lower() for s in _TOKEN.findall(t or "")
            if s.lower() not in _STOP and len(s) > 2]


def tf(toks: list[str]) -> dict[str, float]:
    c = Counter(toks); n = max(1, sum(c.values()))
    return {t: v / n for t, v in c.items()}


def build_idf(docs: list[list[str]]) -> dict[str, float]:
    df: Counter = Counter()
    for d in docs:
        for t in set(d):
            df[t] += 1
    N = len(docs)
    return {t: math.log((N + 1) / (v + 1)) + 1 for t, v in df.items()}


def tfidf(toks: list[str], idf: dict[str, float]) -> dict[str, float]:
    t = tf(toks)
    di = math.log(2)
    return {k: v * idf.get(k, di) for k, v in t.items()}


def cosine(a: dict, b: dict) -> float:
    common = set(a) & set(b)
    if not common: return 0.0
    num = sum(a[k] * b[k] for k in common)
    da = math.sqrt(sum(v * v for v in a.values()))
    db = math.sqrt(sum(v * v for v in b.values()))
    return num / (da * db) if da and db else 0.0


def main() -> int:
    k_top = int(sys.argv[1]) if len(sys.argv) > 1 else 5

    # Atlas quotes corpus (already extracted by method3)
    quotes = [json.loads(l) for l in open(QUOTES_OUT)]
    qtoks = [tokenize(q["quote"]) for q in quotes]
    idf = build_idf(qtoks)
    qvecs = [tfidf(t, idf) for t in qtoks]

    # Population J — joint anomalies under Plain prompting (m2 Arm P)
    j_rows = [json.loads(l) for l in open(M2_OUT) if l.strip()]
    j_hyps = [{"hyp_id": f"j_{r['anomaly_id']}",
               "anomaly_id": r["anomaly_id"],
               "pop": "joint",
               "text": r["hP"]}
              for r in j_rows if "error" not in r and r.get("hP")]

    # Population N — non-joint anomalies under reflect ("C") from genexp16
    n_rows = [json.loads(l) for l in open(GENEXP_OUT) if l.strip()]
    n_hyps = [{"hyp_id": f"n_{r['anomaly_id']}",
               "anomaly_id": r["anomaly_id"],
               "pop": "native",
               "text": r["hC"]}
              for r in n_rows if "error" not in r and r.get("hC")]

    print(f"Population J (Atlas-selected joint anomalies, Plain prompting): {len(j_hyps)}",
          file=sys.stderr)
    print(f"Population N (aigraph-native non-joint anomalies, reflect):    {len(n_hyps)}",
          file=sys.stderr)

    out = []
    for h in j_hyps + n_hyps:
        hv = tfidf(tokenize(h["text"]), idf)
        sims = [(cosine(hv, v), i) for i, v in enumerate(qvecs)]
        sims.sort(reverse=True)
        top = [{"idx": i, "sim": round(s, 3),
                "dim": quotes[i]["dimension"],
                "severity": quotes[i]["severity"],
                "quote": quotes[i]["quote"][:400]}
               for s, i in sims[:k_top]]
        out.append({
            "hyp_id": h["hyp_id"],
            "anomaly_id": h["anomaly_id"],
            "pop": h["pop"],
            "hypothesis_text": h["text"][:800],
            "top_k_atlas": top,
        })

    op = _REPO / "artifacts/atlas_test/method7_judge_input.jsonl"
    with open(op, "w") as fh:
        for r in out:
            fh.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"wrote {len(out)} judge-input records → {op}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
